services:
  mysql :
    image : mysql:8
    container_name: database
    env_file:
      - .env
      - .env.prod
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - server

  node:
    build:
      context: ./
      dockerfile: dockerfile
    platform: linux/amd64
    container_name: server
    env_file:
      - .env
      - .env.prod
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    stdin_open: true
    tty: true
    networks:
      - server
volumes:
    db:
networks:
  server: