version: '3.8'

services:
  my_jenkins:
    container_name: my_jenkins
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
    user: root
    restart: unless-stopped